### PR TITLE
Complete challenge

### PR DESCRIPTION
**Pull request by bronsonavila**

### CODE REVIEW

**Review by taesup — APPROVED** [review]
So it works fine as is, but it's a good idea to take in some of the optimizations we went over in class. Things like creating the numbers array in your constructor, doing most of the work in a single `.reduce` function, and making line 39 more readable.

**Comment by bronsonavila** [comment]
Thank you for the review. I have a question regarding the comment about "creating the numbers array in your constructor." 

The `challenge_6.js` file initially provides the constructor on line 9, and it contains a single `naturalNumbers` property:

```
function SumOfASquare(naturalNumbers) {
  this.naturalNumbers = naturalNumbers;
}
```

An instruction to "do work here" appears immediately below the provided constructor. Based on these instructions, it appears that I should not be editing anything above line 13. Thus, I would not be allowed to do something like this to the constructor because it appears before line 13:

```
function SumOfASquare(naturalNumbers) {
  this.naturalNumbers = naturalNumbers;
  this.numbersArray = [];
  for (let i = this.naturalNumbers; i > 0; i--) {
    numbersArray.push(i);
  }
}
```

Rather, I would need to find a way to add a property to the constructor somewhere after line 13. However, [this page regarding constructors](https://www.w3schools.com/js/js_object_constructors.asp) states, "You cannot add a new property to an object constructor the same way you add a new property to an existing object[...] To add a new property to a constructor, you must add it to the constructor function[.]"

Based on this limitation, I do not see a way that I could add a `numbersArray` property to the constructor without violating the requirement that all work be performed after line 13 (and I have been unable to find a way to do so). Is there actually a way to add to the constructor from outside of the constructor?

**Comment by taesup** [comment]
Yea basically ignore that comment on line 13, you can do all the work in the constructor.

**Comment by bronsonavila** [comment]
Understood. Thank you, Ed. 👍

**Pull request closed without merging**
